from pybricks.parameters import Port
#Ports
PORT_MOTOR_LEFT = Port.B
PORT_MOTOR_RIGHT = Port.C
PORT_SENSOR_COLOR = Port.S3
PORT_SENSOR_DISTACES = Port.S2

# Var Colors
LINE = 6
FLOOR = 25
LIMIT = (LINE + FLOOR) / 2

# VAR DISTANCE
DISTANCE_UPPER = 30
DISTANCE_LOWER = 10
LIMIT_OBSTACLE = (DISTANCE_UPPER - DISTANCE_LOWER) / 2

# VAR MOTORS
WHEL_DIAMETER = 55.5
AXEL_TRACK = 117
TURN_CORRECTION = 1
SPEED = 350
GAIN = 0.6
